# Generated by Django 5.1 on 2024-08-26 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_groups_and_more'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('token_blacklist', '0012_alter_outstandingtoken_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomUser',
            new_name='CustomUserObject',
        ),
    ]
