trigger:
  branches:
    include:
      - main
      - dev
      - prod

pool:
  vmImage: ubuntu-latest

variables:
  nodeVersion: '18.17.0'
  frontendDirectory: 'frontend'

stages:
- stage: Deploy
  displayName: 'Deploy the web application'
  jobs:
  - deployment: Deploy
    pool:
      vmImage: ubuntu-20.04
    environment: dev  # change to production for the prod branch
    variables:
      - group: Release
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: drop
          - task: AzureWebApp@1
            displayName: 'Azure App Service Deploy: website'
            inputs:
              azureSubscription: 'ASDRestaurant'  # Name of your Azure service connection
              appName: '$(WebAppName)'  # Name of your Azure App Service
              package: '$(Pipeline.Workspace)/drop/*.zip'
    condition: eq(variables['Build.SourceBranchName'], 'main')  # Deploy only on main branch
