# Generated by Django 3.2.19 on 2024-10-28 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20241028_1556'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_items',
            new_name='order_item',
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('PR', 'Priority'), ('SC', 'Scheduled'), ('ST', 'Standard')], default='ST', max_length=3),
        ),
    ]
