# Generated by Django 3.2.19 on 2024-10-28 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0004_remove_menuitem_stock'),
        ('orders', '0005_auto_20241028_1558'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderItems',
            new_name='OrderItem',
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('ST', 'Standard'), ('SC', 'Scheduled'), ('PR', 'Priority')], default='ST', max_length=3),
        ),
    ]
