# Generated by Django 3.2.19 on 2024-10-28 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20241028_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='instructions',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('PR', 'Priority'), ('SC', 'Scheduled'), ('ST', 'Standard')], default='ST', max_length=3),
        ),
    ]
