# Generated by Django 3.2.19 on 2024-10-28 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20241028_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('ST', 'Standard'), ('PR', 'Priority'), ('SC', 'Scheduled')], default='ST', max_length=3),
        ),
    ]
