# Generated by Django 5.1 on 2024-10-28 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20241028_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('SC', 'Scheduled'), ('ST', 'Standard'), ('PR', 'Priority')], default='ST', max_length=3),
        ),
    ]
