# Generated by Django 3.2.19 on 2024-09-18 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('option_id', models.AutoField(primary_key=True, serialize=False)),
                ('option_name', models.CharField(max_length=100)),
                ('option_price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
